import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";
import Header from "../components/Header";
import { useState } from "react";

const graphcms = new GraphQLClient(
  "https://api-ap-south-1.hygraph.com/v2/cla42z6uz3aqt01uo6l9r7p7o/master"
);
const QUERY = gql`
  {
    posts {
      id
      title
      date
      slug
      description
      category
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverImage {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}
export default function Home({ posts }) {
  const [data, setData] = useState(posts);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setData={setData} data={data} />
      <main className={styles.main}>
        {data.map((post) => (
          <BlogCard
            title={post.title}
            category={post.category}
            author={post.author}
            coverImage={post.coverImage}
            description={post.description}
            key={post.id}
            date={post.date}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
